AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Sample Template for CFN Init

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.

Resources:
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP access via port 80 and SSH access via port 22
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: !Ref SSHLocation

  WebServerHost: #this will be referenced in Properties section below for User Data script execution
    Type: AWS::EC2::Instance
    Metadata:
      Comment: Install a simple PHP application
      
      #lot of magic happens here - only useful if triggered by UserData section in Properties section below
      AWS::CloudFormation::Init:
        config:
          packages: #list of packages you want on Linux OS (apt, msi, python, rpm, rubygems, yum)
            yum:
              httpd: [] #empty array means latest version
              php: []

          groups: #user groups
            apache: {} #group is whatever id {}, optionally give it a string id

          users: #define users and what groups they belong to
            "apache": #apache user
              groups:
                - "apache" #belongs to group "apache"

          sources: #download file and place it on ec2 instance (in this case, aws cli)
            "/home/ec2-user/aws-cli": "https://github.com/aws/aws-cli/tarball/master"

          files: #create files on ec2 instance (can be from url or inline)
            "/tmp/cwlogs/apacheaccess.conf": #filename is the key
              content: !Sub | #!Sub here means you replace text by value where there is $
                [general]
                state_file= /var/awslogs/agent-state
                [/var/log/httpd/access_log]
                file = /var/log/httpd/access_log
                log_group_name = ${AWS::StackName} 
                log_stream_name = {instance_id}/apache.log
                datetime_format = %d/%b/%Y:%H:%M:%S
              mode: '000400'
              owner: apache
              group: apache

            #file 2
            "/var/www/html/index.php":
              content: !Sub |
                <?php
                echo '<h1>AWS CloudFormation sample PHP application for ${AWS::StackName}</h1>';
                ?>
              mode: '000644'
              owner: apache
              group: apache

            #file 3 -  this is the daemon looking for metadata changes (15 minute delay)
            "/etc/cfn/cfn-hup.conf":
              content: !Sub |
                [main]
                stack=${AWS::StackId}
                region=${AWS::Region}
              mode: "000400"
              owner: "root"
              group: "root"

            #file 4 - trigger and path to look for metadata changes
            "/etc/cfn/hooks.d/cfn-auto-reloader.conf":
              content: !Sub |
                [cfn-auto-reloader-hook]
                triggers=post.update
                path=Resources.WebServerHost.Metadata.AWS::CloudFormation::Init
                action=/opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource WebServerHost --region ${AWS::Region}
              mode: "000400"
              owner: "root"
              group: "root"

          commands: #USE THIS AS LAST RESORT, IF FILES CANT GET THE JOB DONE
            test:
              command: "echo \"$MAGIC\" > test.txt"
              env:
                MAGIC: "I come from the environment!"
              cwd: "~" #current working directory - root in this case

          services: #useful for launching services on instance launch
            sysvinit:
              httpd: 
                enabled: 'true'
                ensureRunning: 'true'
              sendmail: #deactivating mails
                enabled: 'false'
                ensureRunning: 'false'

    CreationPolicy:
      ResourceSignal: #waiting for a resource signal good health in 5 minutes
        Timeout: PT5M

    Properties:
      ImageId: ami-a4c7edb2
      KeyName:
        Ref: KeyName
      InstanceType: t2.micro
      SecurityGroups:
      - Ref: WebServerSecurityGroup
      UserData:
        "Fn::Base64":
          !Sub |
            #!/bin/bash -xe
            # Get the latest CloudFormation package
            yum update -y aws-cfn-bootstrap
            # Start cfn-init
            /opt/aws/bin/cfn-init -s ${AWS::StackId} -r WebServerHost --region ${AWS::Region} || error_exit 'Failed to run cfn-init'
            # Start up the cfn-hup daemon to listen for changes to the EC2 instance metadata
            /opt/aws/bin/cfn-hup || error_exit 'Failed to start cfn-hup'
            # All done so signal success - was there an error (-e $?) if so, call stack by stack ID
            /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackId} --resource WebServerHost --region ${AWS::Region}

Outputs:
  InstanceId:
    Description: The instance ID of the web server
    Value:
      Ref: WebServerHost

  WebsiteURL:
    Value:
      !Sub 'http://${WebServerHost.PublicDnsName}'
    Description: URL for newly created LAMP stack

  PublicIP:
    Description: Public IP address of the web server
    Value:
      !GetAtt WebServerHost.PublicIp